# Generated by Django 3.2.6 on 2021-08-29 08:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('VSA_website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doubt',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video_upload',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video_upload',
            name='video_file',
            field=models.FileField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='video_upload',
            name='video_name',
            field=models.IntegerField(default=0),
        ),
    ]
