# Generated by Django 3.2.6 on 2021-08-29 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VSA_website', '0002_auto_20210829_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video_upload',
            name='video_file',
            field=models.FileField(null=True, upload_to='videos/', verbose_name=''),
        ),
    ]
