# Generated by Django 3.2.6 on 2021-08-30 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VSA_website', '0003_alter_video_upload_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='doubt',
            name='answer',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
