# Generated by Django 3.2.6 on 2021-08-30 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VSA_website', '0004_doubt_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='doubt',
            name='question',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
